#include "menus/menu_hundo_saves/include/hundo_saves_menu.h"
#include "gz_flags.h"
#include "save_specials.h"
#include "save_manager.h"
#include "rels/include/defines.h"
#include "menus/utils/menu_mgr.h"

KEEP_FUNC HundoSavesMenu::HundoSavesMenu(Cursor& cursor)
	: Menu(cursor), lines{
    {"mss", MSS_HUNDO, "manual superswim to dragon roost island"},
    {"rock jump", ROCK_JUMP, "dragon roost island, after getting the wind waker"},
    {"mail game", MAIL_GAME, "the mail mini game in dragon roost island"},
	{"drc", DRC, "the swordless dragon roost cavern segment"},
	{"drc storage", DRC_STORAGE, "chest storage in dragon roost cavern"},
	{"seamwalk", SEAMWALK, "walk on the wall with chest storage collision"},
	{"after warp pot", AFTER_WARP_POT, "segment before dragon roost cavern miniboss"},
	{"drc miniboss", DRC_MINIBOSS, "swordless miniboss for grappling hook"},
	{"drc bk skip", DRC_BKSKIP, "chest storage boss key skip"},
	{"gohma", GOHMA, "the dragon roost cavern boss"},
	{"zephos", ZEPHOS, "zephos cutscene skip with letter to mom"},
	{"windfall swim", WINDFALL_SWIM, "at dragon roost, about to superswim to windfall"},
	{"windfall 1", WINDFALL1, "the first windfall trip"},
	{"forest haven swim", FH_SWIM_HUNDO, "at windfall, double storage superswim to forest haven"},
	{"wind waker dive", WW_DIVE, "at forest haven, wind waker dive to enter forest haven"},
	{"deku tree cs skip", DEKU_CS, "at forest haven, about to do deku tree cutscene skip"},
	{"to leaf", TO_LEAF, "at forest haven, about to get the deku leaf"},
	{"swordless forest", ENTER_FOREST, "at outset, going to forest of fairies"},
	{"wallet", WALLET, "roll clip to fairy fountain for the wallet"},
	{"invisible ship", INVISIBLE_SHIP, "deku leaf from the watchtower to the invisible pirate ship"},
	{"ropes 1", ROPES1, "inside pirate ship, about to play ropes 1 minigame"},
	{"ship door storage", DOOR_STORAGE, "on pirate ship, door storage before ff1"},
	{"ropes 2", ROPES2, "inside pirate ship, about to play ropes 2 minigame"},
	{"ff1", FF1_HUNDO, "the first forsaken fortress segment"},
	{"windfall 2", WINDFALL2, "the second windfall trip"},
	{"forest haven swim 2", FH_SWIM2, "the second forest haven superswim to beedle"},
	{"enter fw", ENTER_FW, "at forest haven, about to enter forbidden woods"},
	{"forbidden woods", FW, "the forbidden woods segment"},
	{"fw chest storage", FW_STORAGE, "the chest storage in forbidden woods"},
	{"fw tingle balloon", FW_BALLOON, "use tingle balloon and chest storage collision to get to top door"},
	{"mothula", MOTHULA, "the forbidden woods miniboss"},
	{"fw basement chart", FW_CHART, "in the basement of forbidden woods, about to get the chart"},
	{"fw bk skip", FW_BKSKIP, "chest storage to get past the boss door"},
	{"kalle demos", KALLE_DEMOS, "the forbidden woods boss"},
	{"east triangle swim", EAST_SWIM, "at forest haven, about to superswim to eastern triangle"},
	{"north triangle swim", NORTH_SWIM, "at eastern triangle, about to superswim to north triangle"},
	{"islet swim", ISLET, "at northern triangle, about to superswim to islet of steel"},
	{"outset swim", OUTSET_SWIM, "at greatfish, about to superswim to outset island"},
	{"grandma bomb clip", JABU, "the clip into grandma's house to get to jabu"},
	{"south triangle swim", SOUTH_SWIM, "at outset island, about to superswim to north triangle"},
	{"totg", TOTG, "the tower of the gods segment"},
	{"jack clip", JACK_CLIP, "skip walking around with the 1st goddess statue"},
	{"second statue", STATUE2, "skip command melody on the 2nd goddess statue"},
	{"darknut", DARKNUT, "the tower of the gods miniboss"},
	{"scales", SCALES, "get past the scales using only one statue"},
	{"boss key", BOSS_KEY, "skip the lasers to get the boss key"},
	{"outside", LASER_SKIP, "get past the beamos outside tower of the gods"},
	{"gohdan", GOHDAN, "the tower of the gods boss"},
	{"ballad of gales", REQUIEM, "get the ballad of gales from cyclos"},
	{"crescent moon sub swim", SUB1_SWIM, "at north triangle, about to superswim to crescent moon submarine"},
	{"crescent moon", CRESCENT, "fish up heart piece, then double chest storage to ff2"},
	{"helmaroc 1", HELMAROC1, "helmaroc skip"},
	{"puzzle skip", PUZZLE_SKIP, "skip the puzzle in hyrule castle to enter the master sword room"},
	{"barrier skip", BARRIER, "outside hyrule castle, about to do barrier skip"},
	{"trials skip", TRIALS, "inside ganon's tower, about to do trials skip"},
	{"light arrow", LIGHT_ARROW, "inside ganon's tower, about to fight phantom ganon for light arrow"},
	{"phantom ganon", PHANTOM_GANON, "at ff2, about to fight phantom ganon"},
	{"enter helmaroc", ENTER_HELMAROC, "chest storage and storage to enter helmaroc 2 without crashing"},
	{"helmaroc 2", HELMAROC2, "the helmaroc fight"},
	{"windfall 3", WINDFALL3, "3rd windfall segment, sploosh and auction"},
	{"gale swim", GALE_SWIM1, "at windfall, about to superswim to gale isle"},
	{"enter gale", GALE, "at gale isle, about to go inside without iron boots"},
	{"fire mountain swim", MOUNTAIN_SWIM, "at gale isle, about to superswim to fire mountain island"},
	{"bracelets", BRACELETS, "at fire mountain island, about to go inside"},
	{"bird's peak swim", PEAK_SWIM, "at fire mountain island, about to superswim to bird's peak rock"},
	{"ice ring swim", ICE_SWIM, "at bird's peak rock, about to superswim to ice ring isle"},
	{"iron boots", IRONS, "at ice ring isle, about to go inside"},
	{"two-eye reef swim 1", TWO_EYE_SWIM1, "at ice ring isle, about to superswim to two-eye reef"},
	{"double magic", DOUBLE_M, "at two-eye reef, on the way to double magic octo"},
	{"early earth temple", EARLY_ET, "enter earth temple without medli with bomb push"},
	{"earth temple", ET, "the earth temple segment"},
	{"blobs room", BLOB, "inside earth temple, before blobs room"},
	{"statue room", STATUE, "inside earth temple, in statue room"},
	{"1st song stone skip", SONG_STONE, "inside earth temple, about to skip the first song stone"},
	{"3rd song stone skip", SONG_STONE3, "inside earth temple, about to skip the third song stone"},
	{"et bk skip", ET_BKSKIP, "inside earth temple, about to skip the boss key"},
	{"jalhalla", JALHALLA, "the earth temple boss"},
	{"after earth temple", AFTER_ET, "the segment post earth temple"},
	{"golf", GOLF, "at horseshoe island"},
	{"golf storage", GOLF_STORAGE, "at horseshoe, about to perform chest storage"},
	{"ghost chart", GHOST_CHART, "at diamond steppe, about to fish up heart piece and enter the island"},
	{"three-eye swim", THREE_EYE_SWIM, "at diamond steppe, about to superswim to three-eye reef"},
	{"three-eye reef", THREE_EYE, "three-eye reef section"},
	{"shark swim", SHARK_SWIM, "at forest haven, about to superswim to shark island"},
	{"shark island", SHARK, "in beedle shop, near shark island"},
	{"needle rock isle", NEEDLE, "the needle rock section"},
	{"five-eye reef", FIVE_EYE, "five-eye reef section"},
	{"eastern fairy", EASTERN_FAIRY, "after bomb upgrade, about to fish up treasure chart"},
	{"gale swim 2", GALE_SWIM2, "at windfall, double storage superswim to gale isle"},
	{"wind temple", WT, "the wind temple segment"},
	{"door clip", DOOR_CLIP, "inside wind temple, about to clip through the door frame"},
	{"hookshot miniboss", HOOKSHOTMB, "the wind temple miniboss"},
	{"two chests room", FIVEHOLES, "the room with two chests"},
	{"big circular room", WIND_CHART, "kill enemies to spawn chest"},
	{"mid-air jumpslash", WIND_JS, "don't fall down here"},
	{"molgera", MOLGERA, "the wind temple boss"},
	{"star isle superswim", STAR_SWIM, "at gale, about to superswim to star isle"},
	{"star isle", STAR_ISLE, "star isle segment"},
	{"ghost ship", GHOST_SHIP, "farm rupees in the ghost ship"},
	{"spectacle minigame", SPECTACLE_MINIGAME, "shoot the ships"},
	{"tingle octo", OCTO_TINGLE, "kill big octo with bombs"},
	{"tingle storage", TINGLE, "at tingle island, about to superswim to headstone"},
	{"stonewatcher", HEADSTONE, "the stonewatcher triforce chart segment"},
	{"fish up triforce shard", HEADWATCHER, "the headwatcher triforce shard segment"},
	{"six-eye sub swim", SUBSIX, "on a platform, about to superswim to six-eye reef submarine"},
	{"cyclops reef", CYCLOPS, "cyclops reef section"},
	{"cyclops superswim", CYCLOPS_SWIM, "at cyclops reef, about to superswim to pawprint"},
	{"pawprint", PAWPRINT, "pawprint island section"},
	{"overlook", OVERLOOK, "the stonewatcher triforce chart segment"},
	{"savage labyrinth", SAVAGE1, "at the beginning of savage labyrinth"},
	{"floor 10", SAVAGE2, "10th floor of the savage labyrinth"},
	{"floor 20", SAVAGE3, "20th floor of the savage labyrinth"},
	{"pig hp", PIG, "feed the pig to collect a heart piece"},
	{"rat submarine", RATSUB, "kill the rats using boomerang"},
	{"angular isles", ANGULAR, "two heart pieces then superswim to bomb island submarine"},
} {}

HundoSavesMenu::~HundoSavesMenu() {}

void HundoSavesMenu::draw() {
    if (GZ_getButtonTrig(BACK_BUTTON)) {
        g_menuMgr->pop();
        return;
    }

    if (GZ_getButtonTrig(GZPad::A)) {
        special HundoSpecials[] = {
            special(MSS_HUNDO, nullptr, SaveMngSpecial_MSSHundo),
            special(ROCK_JUMP, SaveMngSpecial_RockJump, nullptr),
            special(MAIL_GAME, SaveMngSpecial_MailGame, nullptr),
			special(DRC, SaveMngSpecial_DRC, nullptr),
			special(DRC_STORAGE, SaveMngSpecial_DRCStorage, nullptr),
			special(SEAMWALK, SaveMngSpecial_Seamwalk, nullptr),
			special(AFTER_WARP_POT, SaveMngSpecial_AfterWarpPot, nullptr),
			special(DRC_MINIBOSS, SaveMngSpecial_DRCMiniboss, nullptr),
			special(DRC_BKSKIP, SaveMngSpecial_DRCBKSkip, nullptr),
			special(GOHMA, SaveMngSpecial_Gohma, nullptr),
			special(ZEPHOS, SaveMngSpecial_Zephos, nullptr),
			special(WINDFALL_SWIM, SaveMngSpecial_WindfallSwim, nullptr),
			special(WINDFALL1, SaveMngSpecial_Windfall1, nullptr),
			special(FH_SWIM_HUNDO, SaveMngSpecial_FHSwim, nullptr),
			special(WW_DIVE, SaveMngSpecial_WWDive, nullptr),
			special(DEKU_CS, SaveMngSpecial_DekuCS, nullptr),
			special(TO_LEAF, SaveMngSpecial_ToLeaf, nullptr),
			special(WALLET, SaveMngSpecial_Wallet, nullptr),
			special(INVISIBLE_SHIP, SaveMngSpecial_InvisibleShip, nullptr),
			special(ROPES1, SaveMngSpecial_Ropes1Hundo, nullptr),
			special(ROPES2, SaveMngSpecial_Ropes2Hundo, nullptr),
			special(ENTER_FW, SaveMngSpecial_EnterFW, nullptr),
			special(FW_STORAGE, SaveMngSpecial_FWStorage, nullptr),
			special(FW_BALLOON, SaveMngSpecial_FWBalloon, nullptr),
			special(MOTHULA, SaveMngSpecial_Mothula, nullptr),
			special(FW_CHART, SaveMngSpecial_FWChart, nullptr),
			special(FW_BKSKIP, SaveMngSpecial_FWBKSkip, nullptr),
			special(KALLE_DEMOS, SaveMngSpecial_KalleDemos, nullptr),
			special(EAST_SWIM, SaveMngSpecial_EastSwim, nullptr),
			special(JABU, SaveMngSpecial_Jabu, nullptr),
			special(SOUTH_SWIM, SaveMngSpecial_SouthSwim, nullptr),
			special(JACK_CLIP, SaveMngSpecial_JackClip, nullptr),
			special(STATUE2, SaveMngSpecial_Statue2, nullptr),
			special(DARKNUT, SaveMngSpecial_Darknut, nullptr),
			special(SCALES, SaveMngSpecial_Scales, nullptr),
			special(BOSS_KEY, SaveMngSpecial_BossKey, nullptr),
			special(LASER_SKIP, SaveMngSpecial_LaserSkip, nullptr),
			special(GOHDAN, SaveMngSpecial_Gohdan, nullptr),
			special(REQUIEM, SaveMngSpecial_Requiem, nullptr),
			special(CRESCENT, SaveMngSpecial_Crescent, nullptr),
			special(BARRIER, SaveMngSpecial_Barrier, nullptr),
			special(TRIALS, SaveMngSpecial_Trials, nullptr),
			special(LIGHT_ARROW, SaveMngSpecial_LightArrow, nullptr),
			special(PHANTOM_GANON, SaveMngSpecial_PhantomGanon, nullptr),
			special(ENTER_HELMAROC, SaveMngSpecial_EnterHelmaroc, nullptr),
			special(GALE, SaveMngSpecial_Gale, nullptr),
			special(MOUNTAIN_SWIM, SaveMngSpecial_MountainSwim, nullptr),
			special(PEAK_SWIM, SaveMngSpecial_PeakSwim, nullptr),
			special(TWO_EYE_SWIM1, SaveMngSpecial_TwoEyeSwim1, nullptr),
			special(EARLY_ET, SaveMngSpecial_TwoEyeSwim1, nullptr),
			special(BLOB, SaveMngSpecial_Blob, nullptr),
			special(STATUE, SaveMngSpecial_Statue, nullptr),
			special(SONG_STONE, SaveMngSpecial_SongStone, nullptr),
			special(SONG_STONE3, SaveMngSpecial_SongStone3, nullptr),
			special(ET_BKSKIP, SaveMngSpecial_ETBKSkip, nullptr),
			special(JALHALLA, SaveMngSpecial_Jalhalla, nullptr),
			special(AFTER_ET, SaveMngSpecial_AfterET, nullptr),
			special(GOLF_STORAGE, SaveMngSpecial_GolfStorage, nullptr),
			special(THREE_EYE_SWIM, SaveMngSpecial_ThreeEyeSwim, nullptr),
			special(SHARK, SaveMngSpecial_Shark, nullptr),
			special(EASTERN_FAIRY, SaveMngSpecial_EasternFairy, nullptr),
			special(DOOR_CLIP, SaveMngSpecial_DoorClip, nullptr),
			special(HOOKSHOTMB, SaveMngSpecial_HookshotMB, nullptr),
			special(FIVEHOLES, SaveMngSpecial_Fiveholes, nullptr),
			special(WIND_CHART, SaveMngSpecial_WindChart, nullptr),
			special(WIND_JS, SaveMngSpecial_WindJS, SaveMngSpecial_WindJSAfter),
			special(MOLGERA, SaveMngSpecial_Molgera, nullptr),
			special(TINGLE, nullptr, SaveMngSpecial_Tingle),
			special(HEADSTONE, SaveMngSpecial_Headstone, nullptr),
			special(SUBSIX, nullptr, SaveMngSpecial_SubSix),
			special(CYCLOPS_SWIM, nullptr, SaveMngSpecial_CyclopSwim),
			special(OVERLOOK, SaveMngSpecial_Overlook, nullptr),
			special(SAVAGE1, SaveMngSpecial_Savage1, nullptr),
			special(SAVAGE2, SaveMngSpecial_Savage2, nullptr),
			special(SAVAGE3, SaveMngSpecial_Savage3, nullptr),
			special(PIG, SaveMngSpecial_Pig, nullptr),
			special(RATSUB, SaveMngSpecial_RatSub, nullptr),

        };

        SaveManager::triggerLoad(cursor.y, "hundo", HundoSpecials,
                                 sizeof(HundoSpecials) / sizeof(HundoSpecials[0]));
        g_menuMgr->hide();
    }

    cursor.move(0, sizeof(lines) / sizeof(lines[0]));
    GZ_drawMenuLines(lines, cursor.y, sizeof(lines) / sizeof(lines[0]));
}
